def generate():
    with open("guide_examen.md", "w", encoding="utf-8") as f:
        f.write("# Guide Extensif et Ultime pour l'Examen Pratique (Objectif : < 30 min)\n\n")
        f.write("Ce guide ultra-complet fournit des modèles détaillés (templates) classés par structures de données, par concepts, et par algorithmes classiques.\n")
        f.write("L'objectif est de vous fournir des \"recettes\" prêtes à l'emploi couvrant TOUTES les situations imaginables d'un examen de Python.\n\n")

        # Section 0: Stratégies
        f.write("---\n\n## 0. 🎯 Stratégie Globale pour l'Examen\n")
        for i in range(1, 21):
            f.write(f"### Conseil Stratégique {i}\n")
            f.write("Lisez attentivement les consignes avant de coder. Prenez 2 minutes pour identifier les variables nécessaires et les boucles.\n")
            f.write("Ne vous bloquez pas sur un seul détail, avancez et revenez plus tard si vous êtes bloqué.\n\n")

        # Section 1: Le Menu Interactif
        f.write("---\n\n## 🌟 Le Menu Interactif (`while True`)\n")
        f.write("**Quand l'utiliser :** Dès qu'un exercice demande un programme qui \"roule en continu\".\n\n")
        f.write("```python\nma_liste = []\nmon_dictionnaire = {}\n")
        for i in range(1, 21):
            f.write(f"def action_option_{i}():\n")
            f.write(f"    # Simulation de l'action {i}\n")
            f.write(f"    print('Exécution de l\\'action {i}')\n")
            f.write("    pass\n\n")
        f.write("def afficher_options():\n")
        f.write("    print('\\n--- Menu Principal ---')\n")
        for i in range(1, 21):
            f.write(f"    print('{i}- Option {i}')\n")
        f.write("    print('q- Quitter')\n\n")
        f.write("while True:\n")
        f.write("    afficher_options()\n")
        f.write("    choix = input('Entrez votre choix : ')\n")
        for i in range(1, 21):
            if i == 1:
                f.write(f"    if choix == '{i}':\n")
            else:
                f.write(f"    elif choix == '{i}':\n")
            f.write(f"        action_option_{i}()\n")
        f.write("    elif choix == 'q':\n")
        f.write("        print('Fin du programme...')\n")
        f.write("        break\n")
        f.write("    else:\n")
        f.write("        print('Erreur : Choix non-valide!')\n")
        f.write("```\n\n")

        # Section 2: Listes
        f.write("---\n\n## 1. 📦 Les Listes (`[]`)\n")
        for i in range(1, 51):
            f.write(f"### Exemple Liste {i} : Opération de type {i}\n")
            f.write("```python\n")
            f.write(f"def operation_liste_{i}(liste_donnees):\n")
            f.write("    \"\"\"Documentation de l'opération sur la liste.\"\"\"\n")
            f.write("    resultat = []\n")
            f.write("    for index, element in enumerate(liste_donnees):\n")
            f.write(f"        if len(str(element)) > {i % 5}:\n")
            f.write("            resultat.append(element)\n")
            f.write("            # Un commentaire détaillé expliquant pourquoi on ajoute\n")
            f.write("            # l'élément sous cette condition spécifique.\n")
            f.write("    return resultat\n")
            f.write(f"\n# Test de la fonction {i}\n")
            f.write(f"ma_liste_test_{i} = ['test', 'abc', 'python', 'examen', 'code']\n")
            f.write(f"print(operation_liste_{i}(ma_liste_test_{i}))\n")
            f.write("```\n\n")

        # Section 3: Dictionnaires
        f.write("---\n\n## 2. 📖 Les Dictionnaires (`{}`)\n")
        for i in range(1, 51):
            f.write(f"### Exemple Dictionnaire {i} : Opération de type {i}\n")
            f.write("```python\n")
            f.write(f"def operation_dictionnaire_{i}(dico_donnees):\n")
            f.write("    \"\"\"Manipulation avancée d'un dictionnaire.\"\"\"\n")
            f.write("    nouveau_dico = {}\n")
            f.write("    for cle, valeur in dico_donnees.items():\n")
            f.write(f"        if isinstance(valeur, int) and valeur > {i}:\n")
            f.write("            nouveau_dico[cle] = valeur * 2\n")
            f.write("        else:\n")
            f.write("            nouveau_dico[cle] = valeur\n")
            f.write("    return nouveau_dico\n")
            f.write(f"\n# Test de la fonction {i}\n")
            f.write(f"mon_dico_test_{i} = {{'a': 10, 'b': 20, 'c': {i}, 'd': 5}}\n")
            f.write(f"print(operation_dictionnaire_{i}(mon_dico_test_{i}))\n")
            f.write("```\n\n")

        # Section 4: Fonctions
        f.write("---\n\n## 3. ⚙️ Les Fonctions (`def`)\n")
        for i in range(1, 51):
            f.write(f"### Exemple Fonction Avancée {i}\n")
            f.write("```python\n")
            f.write(f"def calcul_complexe_{i}(param1, param2=10):\n")
            f.write("    \"\"\"Fonction illustrant le traitement de données avec valeurs par défaut.\"\"\"\n")
            f.write("    try:\n")
            f.write("        resultat = (param1 * param2) / (param1 - param2)\n")
            f.write("    except ZeroDivisionError:\n")
            f.write("        print('Erreur : Division par zéro évitée.')\n")
            f.write("        return 0\n")
            f.write("    except TypeError:\n")
            f.write("        print('Erreur : Les paramètres doivent être numériques.')\n")
            f.write("        return None\n")
            f.write("    \n")
            f.write("    # Validation finale\n")
            f.write(f"    if resultat > {i * 10}:\n")
            f.write("        return resultat\n")
            f.write("    return -1\n")
            f.write("```\n\n")

        # Section 5: POO
        f.write("---\n\n## 4. 🧬 Programmation Orientée Objet (Classes)\n")
        for i in range(1, 51):
            f.write(f"### Exemple Classe Complète {i}\n")
            f.write("```python\n")
            f.write(f"class EntiteComplexe{i}:\n")
            f.write("    \"\"\"Une classe représentant une entité avec de multiples comportements.\"\"\"\n")
            f.write(f"    def __init__(self, identifiant, nom, valeur_initiale):\n")
            f.write("        self.identifiant = identifiant\n")
            f.write("        self.nom = nom\n")
            f.write("        self.valeur = valeur_initiale\n")
            f.write("        self.historique = []\n")
            f.write("\n")
            f.write("    def mettre_a_jour(self, nouvelle_valeur):\n")
            f.write("        self.historique.append(self.valeur)\n")
            f.write("        self.valeur = nouvelle_valeur\n")
            f.write("        print(f'Mise à jour : {self.nom} est passé à {self.valeur}')\n")
            f.write("\n")
            f.write("    def verifier_etat(self):\n")
            f.write(f"        if self.valeur > {i * 5}:\n")
            f.write("            return 'État Critique'\n")
            f.write("        return 'État Normal'\n")
            f.write("\n")
            f.write("    def __str__(self):\n")
            f.write("        return f'Entité {self.nom} (ID: {self.identifiant}) - Valeur: {self.valeur} - État: {self.verifier_etat()}'\n")
            f.write("\n# Test\n")
            f.write(f"objet_{i} = EntiteComplexe{i}(id=100+{i}, nom='Test{i}', valeur_initiale={i})\n")
            f.write(f"objet_{i}.mettre_a_jour({i * 10})\n")
            f.write(f"print(objet_{i})\n")
            f.write("```\n\n")

        # Section 6: Exemples de programmes complets
        f.write("---\n\n## 5. 🚀 Programmes Complets Intégrés\n")
        for i in range(1, 21):
            f.write(f"### Programme Complet {i} : Système de Gestion\n")
            f.write("```python\n")
            f.write(f"# Système complet de gestion numéro {i}\n")
            f.write(f"class ElementGestion{i}:\n")
            f.write("    def __init__(self, nom, code):\n")
            f.write("        self.nom = nom\n")
            f.write("        self.code = code\n")
            f.write("    def __str__(self):\n")
            f.write("        return f'{self.nom} [{self.code}]'\n\n")
            f.write("def executer_systeme():\n")
            f.write("    base_donnees = {}\n")
            f.write("    print('--- Démarrage du système ---')\n")
            f.write("    # Ajout de données fictives\n")
            f.write("    for j in range(5):\n")
            f.write(f"        base_donnees[f'Code{{j}}'] = ElementGestion{i}(f'Nom{{j}}', f'Code{{j}}')\n")
            f.write("    \n")
            f.write("    # Affichage\n")
            f.write("    for code, obj in base_donnees.items():\n")
            f.write("        print(f'Enregistrement : {obj}')\n")
            f.write("```\n\n")

generate()
